# Site settings
title:       Type
email:       ''
description: ''
baseurl:     '/type'
url:         'https://jakobhillebrand.github.io/type/'
twitter:     ''
github:      ''
instagram:   ''
facebook:    ''



markdown:  kramdown
permalink: pretty
paginate:  6

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages
  
exclude:
  vendor

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
  - values:
      permalink: /:basename:output_ext
